server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/joangarciamira/microservicios-tutorial
          search-paths: config-data
      discovery:
        enabled: true
  application:
    name: config-service
